### ISSUE TITLE
Problems with recursive events

### ISSUE THREAD

**Issue by StefanoCremona** [ennswi/AndroidCaldavSyncAdapater#13] opened 2015-04-21 10:29 UTC
Hi,
after creating (maybe with thunderbird/lightning) a recursive event (ex: every sunday at 10:00 am) and changing one item dates (ex.: from sunday to monday), the sincronization on my mobile device shows only the original event, not the new one.
Non problem with other desktop clients.

Thanks

**Comment by Enrico204** [comment] 2015-12-22 07:26
Hi @StefanoCremona can you please check if HEAD in develop still have this issue? Thanks ;-)

**Comment by ennswi** [comment] 2015-12-22 12:14
Hi @Enrico204 this issue is still in develop.

Thanks for contributing.

**Comment by Enrico204** [comment] 2015-12-22 18:29
Hi @ennswi , I'll double-check EXINFOs, I think that the issue is on TimeZone handling (eg. Android seems to accepts only EXINFOs in UTC; .ics may have EXINFOs in local time). Which TimeZone and server do you have?

**Comment by ennswi** [comment] 2015-12-22 19:31
TimeZone is GMT + 01:00 GERMANY.
I'm using owncloud for syncing.

**Comment by ennswi** [comment] 2015-12-23 15:14
Hallo @Enrico204,

I'll check this again,
deletion of single events works fine.

moving an single event doesn't work.

**Comment by Enrico204** [comment] 2015-12-23 15:30
I just noticed that if you delete a single item on a recurring event, you'll see a duplicated event (also marked as deleted). It's definitely an issue on modify/delete part. I'll check this evening.

**Comment by Enrico204** [comment] 2015-12-24 16:49
Ok that's what I'm getting: when you delete a single item on recurring event, Android create a new event (not recurring) with the same infos as the original item, also marked as deleted. That's why the adapter is doing fuzzy things with events...

**Comment by Enrico204** [comment] 2015-12-25 18:24
I did some work on deletion/modify of single item in a recurring event, and it should be fixed right now ;-)

**Comment by ennswi** [comment] 2015-12-26 11:24
@enrico,

it works great.
But now i have some crashes in the calendar APP.

And it would be Great if you can test these on Thunderbird or  an another desktop Application. 
Wich move  single events correctly.

**Comment by Enrico204** [comment] 2015-12-26 11:31
I will. By now I've tested my code with ownCloud/DAVical and OSX Calendar app ;-)

**Comment by Enrico204** [comment] 2015-12-26 14:49
@ennswi I cannot reproduce that crashes, can you please give me some hints (eg. logcat?).

I've tested Thunderbird and I noticed that Android Calendar cannot handle "RECURRENCE-ID" (ICS parameter of VEVENT). I think that we need to write some workaround...

**Comment by ennswi** [comment] 2015-12-27 10:48
It is possible, that the chrashes are related to the cutom rom.

**Comment by Enrico204** [comment] 2015-12-28 07:00
If you can reproduce that crash, may be interesting look at the stack trace to find out if we can write a workaround for that.

**Comment by ennswi** [comment] 2016-01-07 12:01
Hallo @Enrico204,
I test different possibilities, and exportet these in ics files.(Thunderbird Lightning)
I look at the exportet ics files and compere the differences.

And thats the results
- The "EXDATE" does not syncronized, it' s missing in the parentEvent.
- The "RECURRENCE-ID" is not required(in this implementation), for the moved event.

It looks like we doesn't need a workaround, we only have to sync the ParentEvent Correctly.

**Comment by Enrico204** [comment] 2016-01-08 23:18
uhm, I'll check this, maybe you're right :-)
Unfortunately I'm quite busy right now, I'll continue my work on this issue in one or two weeks

**Comment by strk** [comment] 2017-05-04 10:32
I'm also experiencing problem with recursive event and exceptions. I'm using version 0.1.1. The Android calendar shows 2 event blocks rather than just one. The .ics file indeed contains 2 events (one recursive and 1 "override"). Thunderbird/Lightning as well as Outlook web both show a single one (the overridden one).

Nextcloud calendar UI has the same problem (shows 2 events).

The overridden entry has a `RECURRENCE-ID`

**Comment by strk** [comment] 2017-05-04 10:53
The nextcloud calendar issue (for reference): https://github.com/nextcloud/calendar/issues/435

**Comment by strk** [comment] 2017-05-04 10:56
Nextcloud/Calendar already fixed this in development. Here's the merged PR, which seems about `Recurrence-ID` handling indeed: https://github.com/nextcloud/calendar/pull/413

**Comment by strk** [comment] 2017-05-04 12:05
FYI: this works fine with [DavDroid](https://f-droid.org/repository/browse/?fdfilter=caldav&fdid=at.bitfire.davdroid)

**Comment by ennswi** [comment] 2017-05-05 16:31
it sounds good, that some fix this.
we have to look, how we can fix this on our way..

**Closed as completed** 2018-06-12 12:41 UTC
Labels: bug
